---
- name: users
  hosts: all
  become: yes
  user: simon
  vars_files:
    user-pubkey.yml
  tasks:
  - name: "users"
    user:
      name: "{{ item.name }}"
      shell: /bin/bash
    loop: "{{ users }}"
    loop_control:
      label: "{{ item.name }}"
  - name: "dir"
    file:
      mode: "0700"
      owner: "{{ item.name }}"
      group: "{{ item.name }}"
      state: directory
      path: "/home/{{ item.name }}/.ssh"
    loop: "{{ users }}"
    loop_control:
      label: "{{ item.name }}"
  - name: "authorized_keys"
    ansible.posix.authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "{{ item.pubkey }}"
    loop: "{{ users }}"
    loop_control:
      label: "{{ item.name }}"
  - name: "sudoer"
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: "^{{ item.name }}"
      line: '{{ item.name }} ALL=(ALL:ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'
    loop: "{{ users }}"
    loop_control:
      label: "{{ item.name }}"