---
- name: check instances
  hosts: localhost
  gather_facts: no
  vars_files:
  - aws_keys.yml
  vars:
    my_region: us-east-1
  tasks:
  - name: Gather info
    community.aws.ec2_instance_info:
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      region: "{{my_region}}"
      filters:
        "tag:name": kubernetes
        instance-state-name: running
    register: ec2_info
  - name: Print info
    debug:
      msg: "{{ item.instance_id }} ({{ item.tags.Name }}) is {{ item.state.name }} on ip {{ item.public_ip_address }}"
    loop: "{{ ec2_info.instances }}"
    loop_control:
      label: "{{ item.instance_id }}"