---
- name: check instances
  hosts: localhost
  gather_facts: no
  vars_files:
  - aws_keys.yml
  vars:
    my_region: us-east-1
  tasks:
  - name: Gather info
    community.aws.ec2_instance_info:
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      region: "{{my_region}}"
      filters:
        "tag:name": kubernetes
    register: ec2_info
  - name: Stop instances
    community.aws.ec2_instance:
      state: stopped
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      region: "{{my_region}}"
      instance_ids: "{{ec2_info | community.general.json_query('instances[*].instance_id')}}"